### PR TITLE
Tracks and mini-playlists and volume level mixing, oh my!

### PR DESCRIPTION
**Pull request by cnejame**
### Eliminated commands:
- `media`
- `image`
- `video`

### Modified commands:
- `play`
- `say`
- `skip`

### Added commands:
- `music`
- `bg`
- `q[ueue]`
- `mvolume`
- `qvolume`
- `pvolume`
- `mskip`
- `qskip`

## Mini-playlists
Content can now be passed, using the 4 media commands (music, bg, queue, and play), in specific sequences to be played in that order, by using commas to separate the URLs. The mini-playlists are treated as a single piece of content, so if a queue is involved (i.e. in musicTrack and queueTrack), all items in the mini-playlist are passed to the track at once, and the next item in the queue won't be passed to the track until all items in the mini-playlist are done playing.

So instead of typing:
`ygor: music http://www.example.com/song1.mp3`
`ygor: music http://www.example.com/song2.mp3`
`ygor: music https://www.youtube.com/watch?v=dQw4w9WgXcQ`

you could instead just type:

`ygor: music http://www.example.com/song1.mp3, http://www.example.com/song2.mp3, https://www.youtube.com/watch?v=dQw4w9WgXcQ`

This also means that for the `bg` command, you can tie together sequences of content that the track will continuously loop through. If something happens to an item in the playlist that renders it unplayable, it will simply be removed from the playlist, and everything else will continue to play.

(multiple commands can still be passed by separating them with semicolons)

## Start and End
You can now set when a video file, sound file, or YouTube video should start and end with all media commands.

e.g.

`ygor: play http://www.example.com/video.mp4 -s 10 -e 15, http://www.example.com/audio.mp3 -e 15.02374 -s 1.29537`

(both `s` and `e` are optional)

## Tracks
There are now 4 tracks that are used to play media and show websites. Commands now work around this track system.

### Command: `music`
The `music` command passes content to the musicTrack through a queue managed in controller.js. Once controller.js is told that musicTrack is done playing the content it last received, it will pass the next content to musicTrack for it to play.

The `music` command accepts videos, sound files, SoundCloud songs, and YouTube videos. Regardless of what is passed, the `music` command shows no visuals as it's contents are hidden, and are only heard.

### Command: `bg`
The `bg` command passes content to the bgTrack immediately through controller.js. Content immediately replaces what was previously there.

The `bg` command accepts images, websites, videos, and YouTube videos. Regardless of what is passed, the `bg` command mutes everything so it is only seen, and not heard.

### Command: `queue` or `q`
The `queue` command passes content to the queueTrack through a queue managed in controller.js. Once controller.js is told that queueTrack is done playing the content it last received, it will pass the next content to queueTrack for it to play.

The `queue` command accepts videos, sound files, SoundCloud songs, and YouTube videos. Visually, it appears in front of the bgTrack, but if an audio file is playing, the queueTrack will be hidden so the bgTrack can be seen.

### Command: `play`
The `play` command has no queue, and passes content straight to the playTrack, where it is played in front of everything else without hesitation, and without replacing what is currently playing in playTrack.

The `play` command accepts videos, sound files, SoundCloud songs, and YouTube videos. Visually, it appears in front of the bgTrack and queueTrack, but if an audio file is playing, the playTrack will be hidden so the bgTrack and queueTrack can be seen.

### Command: `say`
`say` does what it always did, except now it uses the playTrack to do it, so it can happen on top of everything else at any given moment.

### Command: `skip`
`skip` does what it always did, except now it sends a skip command to both the musicTrack and the queueTrack at the same time.

### Command: `mskip`
Sends a skip command to the musicTrack. Whatever is next in the lineup will simply seek to the end time it usually should, and the events that happen after this will happen as though the media reached its end time naturally.

### Command: `qskip`
Sends a skip command to the queueTrack. Whatever is next in the lineup will simply seek to the end time it usually should, and the events that happen after this will happen as though the media reached its end time naturally.

## Volume
There is now a master volume which is controlled by the `volume` command, just as it has always been done. But now the musicTrack, queueTrack, and playTrack each have their own volume levels that are relative to this master volume. Their commands are as follows:

### Command: `mvolume`
Controls the volume for the musicTrack. It works identically to the volume command syntactically.

### Command: `qvolume`
Controls the volume for the queueTrack. It works identically to the volume command syntactically.

### Command: `pvolume`
Controls the volume for the playTrack. It works identically to the volume command syntactically.

## Errors
ygor will now flash a quick piece of text if something has an error (e.g. this youtube video can not be embedded) to give you a better idea of why something may not have played when it should have.

### CODE REVIEW

**Comment by tamentis** [comment]
Let's make small increment changes next time, large diffs like that are going to take several passes, let's start with a first pass:

Style:
 - run go format and go lint
 - use tabs for indentation
 - capitalize and punctuate your sentences in comments

General:
 - don't build JSON by concatenating strings, make a struct and serialize it with the json module
 - don't invent a new way to parse commands, use the command-line syntax (e.g. media -e 123123 -s 123123)
 - since we have Angular and jQuery loaded, use those to build elements instead of default JavaScript DOM manipulation tools

**Comment by cnejame** [comment]
Alrighty, I implemented those changes. I had no idea Go had a JSON module, let alone one that could just parse a struct like that. It's really convenient, especially considering the use of tags and exported/unexported fields.

**Comment by dglloyd** [comment]
why you merge conflict.

**Comment by cnejame** [comment]
conflicts have been resolvified.

**Comment by cnejame** [comment]
I threw in some more optimizations and added SoundCloud support on the music, queue, and play tracks.

**Comment by cnejame** [comment]
Added Vimeo support on the music, bg, queue, and play tracks

**Comment by tamentis** [comment]
Regarding volume, instead of having multiple commands, we should have the main command take an optional -t parameter (e.g. volume -t music or volume -t sounds).  It's easy enough to alias shortcuts.

Similar comment on q/queue, I wouldn't define shortcuts as commands, same for skip.

Instead of queue, music and play, use:
 - music (queues everything, own track)
 - video
 - sound
Both video and sound are meant to replace "queue", one will do image+audio, the other one just audio. "video", "sound" and "say" will all share the same queue.

**Comment by cnejame** [comment]
renamed branch to "overhaul-proposal". Smaller changes will be made in a different branches for easier organization, naming, merging, and pull-requests for separate, independent changes.

**Pull request closed without merging**
